In [5]:
import os
import pymysql
import pandas as pd
import geopandas as gp
from shapely.geometry import Point
from sqlalchemy import create_engine
from configparser import ConfigParser

ImportError: cannot import name 'no_default'

In [4]:
dbname = os.getenv('dbname')
dbpasswd = os.getenv('dbpasswd')
dbuser = os.getenv('dbuser')
dbhost = os.getenv('dbhost')
dbport = os.getenv('dbport')

In [5]:
cnx = create_engine('mysql+pymysql://'+dbuser+':'+dbpasswd+'@'+dbhost+':'+str(dbport)+'/'+dbname, echo=False)

TypeError: must be str, not NoneType

Data downloaded from [National Monuments Service - Archaeological Survey of Ireland](http://webgis.archaeology.ie/historicenvironment/)

In [4]:
smr = pd.read_csv('data/Archaeology25112016.csv')

In [5]:
smr.head()

,ENTITY_ID,CLASSCODE,NAT_GRID_E,NAT_GRID_N,ITM_E,ITM_N,CLASSDESC,SMRS,TLAND_NAMES,Lat,Lon,Link
0,WI03373,PROM,334458.7779,192367.7480,734380.0,692403.0,Promontory fort - coastal,WI031-111----,DUNBUR HEAD,52.965537,-5.999549,http://webgis.archaeology.ie/HistoricEnvironme...
1,WI03372,PROM,334081.7028,191571.5707,734003.0,691607.0,Promontory fort - coastal,WI031-110----,DUNBUR HEAD,52.958482,-6.005486,http://webgis.archaeology.ie/HistoricEnvironme...
2,WI01172,CHUR,333821.6321,193090.9024,733743.0,693126.0,Church,WI025-017001-,DUNBUR HEAD,52.972190,-6.008727,http://webgis.archaeology.ie/HistoricEnvironme...
3,WI01189,CAVE,333809.6295,193089.9021,733731.0,693125.0,Cave,WI025-038----,DUNBUR HEAD,52.972184,-6.008906,http://webgis.archaeology.ie/HistoricEnvironme...
4,WI03369,PROM,333725.6113,193078.8991,733647.0,693114.0,Promontory fort - coastal,WI025-109----,DUNBUR HEAD,52.972107,-6.010160,http://webgis.archaeology.ie/HistoricEnvironme...

Data downloaded from [National Monuments Service - underwater-archaeology/wreck-viewer](https://dahg.maps.arcgis.com/apps/webappviewer/index.html?id=89e50518e5f4437abfa6284ff39fd640)

In [5]:
wrecks = pd.read_csv('data/Wrecks_April_2018.csv',encoding='ISO-8859-1')

In [9]:
wrecks.tail()

,OBJECTID,Wreck_Name,Wreck_No,Classification,Place_of_Loss,Date_of_Loss,DD_Lat,DD_Long,Source_of_Co_ordinate,Description,Record_Source,Date_of_Loss_Year_Only
17963,17964,Unknown,W18577,Unknown,"Ballyheigue Strand, 310m SW of Ballyheigue car...",circa. 1750-1825,52.38512,-9.83646,National Monuments Service,When sands shift the remains of a wooden wreck...,"Kelleher 2015, 16-20; Kelleher, 2018; Murray, ...",1825.0
17964,17965,Unknown,W18578,Unknown,"Fornaght Strand, Waterford Harbour, Waterford",Unknown,52.17780,-6.96917,National Monuments Service,Remains of a wooden wreck lie partially expose...,National Monuments Service,NaN
17965,17966,Unknown,W18579,Unknown,"Banna Strand, NW of Tralee",Unknown,52.34839,-9.83617,Laurence Dunne,Wooden wreck.\n----------------------------,Laurence Dunne,NaN
17966,17967,Unknown,W18580,Unknown,"Banna Strand, NW of Tralee",Unknown,52.34822,-9.83617,Laurence Dunne,Wooden wreck.\n----------------------------,Laurence Dunne,NaN
17967,17968,Unknown,W18581,Unknown,"Bray Head, Valentia, 25nm WSW",Unknown,51.78509,-11.07967,GSI Wreck Data,Wreck surveyed by the Celtic Explorer in 2005 ...,GSI Wreck Data,NaN

In [6]:
# remove unneeded columns
smr_cleaned = smr.drop(['ENTITY_ID','NAT_GRID_E','NAT_GRID_N','ITM_E', 'ITM_N'], axis = 1)

# rename coords
smr_cleaned.rename(columns = {'Lat':'lat', 'Lon':'lng'}, inplace = True)

#set name
smr_cleaned['title'] = smr_cleaned['CLASSDESC']

#set type
smr_cleaned['type'] = 'smr'

smr_cleaned.head()

,CLASSCODE,CLASSDESC,SMRS,TLAND_NAMES,lat,lng,Link,title,type
0,PROM,Promontory fort - coastal,WI031-111----,DUNBUR HEAD,52.965537,-5.999549,http://webgis.archaeology.ie/HistoricEnvironme...,Promontory fort - coastal,smr
1,PROM,Promontory fort - coastal,WI031-110----,DUNBUR HEAD,52.958482,-6.005486,http://webgis.archaeology.ie/HistoricEnvironme...,Promontory fort - coastal,smr
2,CHUR,Church,WI025-017001-,DUNBUR HEAD,52.972190,-6.008727,http://webgis.archaeology.ie/HistoricEnvironme...,Church,smr
3,CAVE,Cave,WI025-038----,DUNBUR HEAD,52.972184,-6.008906,http://webgis.archaeology.ie/HistoricEnvironme...,Cave,smr
4,PROM,Promontory fort - coastal,WI025-109----,DUNBUR HEAD,52.972107,-6.010160,http://webgis.archaeology.ie/HistoricEnvironme...,Promontory fort - coastal,smr

In [7]:
niah = pd.read_csv('data/NIAH161116.csv',encoding='ISO-8859-1')

In [8]:
niah.head()

,REG_NO,NAME,NUMBER,STREET1,STREET2,TOWN,TOWNLAND,COUNTY,COUNTY_ID,PLANAUTH,...,X_COORD,Y_COORD,X_COORD_ITM,Y_COORD_ITM,LATITUDE,LONGITUDE,IMAGE_LINK,WEBSITE_LINK,SURVEY_ID,Link
0,31205009,Saint Tiernan's Catholic Church,NaN,Chapel Street,NaN,Crossmolina,CARTRONGILBERT [TIRA. BY.],Mayo,MA,MA,...,113764.0,317350.0,513734.0,817360.0,54.098086,-9.318892,http://www.buildingsofireland.ie/niah/images/s...,http://www.buildingsofireland.ie/niah/search.j...,SURV034,http://webgis.buildingsofireland.ie/HistoricEn...
1,31205012,McMorrow's,NaN,Mullenmore Street,NaN,Crossmolina,CARTRONGILBERT [TIRA. BY.],Mayo,MA,MA,...,113809.0,317531.0,513779.0,817540.0,54.099710,-9.318255,http://www.buildingsofireland.ie/niah/images/s...,http://www.buildingsofireland.ie/niah/search.j...,SURV034,http://webgis.buildingsofireland.ie/HistoricEn...
2,31205013,Crossmolina Glebe House or Crossmolina Rectory,NaN,NaN,NaN,Crossmolina,GLEBE [TIRA. BY. C.MOL. PH.],Mayo,MA,MA,...,114161.0,317940.0,514131.0,817949.0,54.103443,-9.312991,http://www.buildingsofireland.ie/niah/images/s...,http://www.buildingsofireland.ie/niah/search.j...,SURV034,http://webgis.buildingsofireland.ie/HistoricEn...
3,31206001,NaN,NaN,NaN,NaN,Foxford,BELLASS,Mayo,MA,MA,...,126809.0,304188.0,526776.0,804200.0,53.981874,-9.116370,http://www.buildingsofireland.ie/niah/images/s...,http://www.buildingsofireland.ie/niah/search.j...,SURV034,http://webgis.buildingsofireland.ie/HistoricEn...
4,31206002,NaN,NaN,NaN,NaN,Foxford,BELLASS,Mayo,MA,MA,...,126848.0,304134.0,526815.0,804146.0,53.981394,-9.115762,http://www.buildingsofireland.ie/niah/images/s...,http://www.buildingsofireland.ie/niah/search.j...,SURV034,http://webgis.buildingsofireland.ie/HistoricEn...

In [20]:
# remove unneeded columns
niah_cleaned = niah.drop(['COUNTY_ID', 'PLANAUTH','X_COORD','Y_COORD','RATING', 'X_COORD_ITM', 'Y_COORD_ITM', 'SURVEY_ID'], axis = 1)

# rename coords
niah_cleaned.rename(columns = {'LATITUDE':'lat', 'LONGITUDE':'lng'}, inplace = True)

#set name
smr_cleaned['title'] = niah_cleaned['NAME']

#set type
niah_cleaned['type'] = 'niah'

niah_cleaned.head()

,REG_NO,NAME,NUMBER,STREET1,STREET2,TOWN,TOWNLAND,COUNTY,COMPOSITION,APPRAISAL,DATEFROM,DATETO,ORIGINAL_TYPE,lat,lng,IMAGE_LINK,WEBSITE_LINK,Link,type
0,31205009,Saint Tiernan's Catholic Church,NaN,Chapel Street,NaN,Crossmolina,CARTRONGILBERT [TIRA. BY.],Mayo,Detached seven-bay double-height Catholic chur...,A church erected under the aegis of Reverend B...,1855.0,1865.0,church/chapel,54.098086,-9.318892,http://www.buildingsofireland.ie/niah/images/s...,http://www.buildingsofireland.ie/niah/search.j...,http://webgis.buildingsofireland.ie/HistoricEn...,niah
1,31205012,McMorrow's,NaN,Mullenmore Street,NaN,Crossmolina,CARTRONGILBERT [TIRA. BY.],Mayo,"Terraced two-bay two-storey house, extant 1838...",A house erected as one of a pair representing ...,1700.0,1838.0,house,54.099710,-9.318255,http://www.buildingsofireland.ie/niah/images/s...,http://www.buildingsofireland.ie/niah/search.j...,http://webgis.buildingsofireland.ie/HistoricEn...,niah
2,31205013,Crossmolina Glebe House or Crossmolina Rectory,NaN,NaN,NaN,Crossmolina,GLEBE [TIRA. BY. C.MOL. PH.],Mayo,Detached two-bay two-storey over part raised b...,A glebe house erected with financial support (...,1810.0,1815.0,house,54.103443,-9.312991,http://www.buildingsofireland.ie/niah/images/s...,http://www.buildingsofireland.ie/niah/search.j...,http://webgis.buildingsofireland.ie/HistoricEn...,niah
3,31206001,NaN,NaN,NaN,NaN,Foxford,BELLASS,Mayo,"Handball alley, built 1901; extant 1925, with ...",A neglected handball alley erected under the a...,1900.0,1905.0,handball alley,53.981874,-9.116370,http://www.buildingsofireland.ie/niah/images/s...,http://www.buildingsofireland.ie/niah/search.j...,http://webgis.buildingsofireland.ie/HistoricEn...,niah
4,31206002,NaN,NaN,NaN,NaN,Foxford,BELLASS,Mayo,"Seven-arch road bridge over river, extant 1895...",A bridge representing an integral component of...,1840.0,1895.0,bridge,53.981394,-9.115762,http://www.buildingsofireland.ie/niah/images/s...,http://www.buildingsofireland.ie/niah/search.j...,http://webgis.buildingsofireland.ie/HistoricEn...,niah

In [14]:
# remove unneeded columns
wrecks_cleaned = wrecks.drop(['OBJECTID','Source_of_Co_ordinate', 'Record_Source', 'Date_of_Loss_Year_Only'], axis = 1)

# rename coords and name 
wrecks_cleaned.rename(columns = {'DD_Lat':'lat', 'DD_Long':'lng', 'Wreck_Name': 'name'}, inplace = True)

#drop wrecks at Null Island
wrecks_cleaned =  wrecks_cleaned[wrecks_cleaned.lat != 0.0]

#set type
wrecks_cleaned['type'] = 'wrecks'

wrecks_cleaned.head()

,name,Wreck_No,Classification,Place_of_Loss,Date_of_Loss,lat,lng,Description,type
21,Connemara (SS),W00022,Steamship,"Louth, Carlingford Lough, Carlingford Bar",03/11/1916,54.01683,-6.06167,"UKHO wreck no. 007600057. An 833-ton, 19-year-...",wrecks
50,James Postlethwaite (MV),W00051,Schooner,"Louth, Carlingford Lough Fairway, 54 03 02N, 0...",11/05/1929,54.05056,-6.15278,The auxiliary wooden three-masted motor schoon...,wrecks
76,Pine (SS),W00077,Steamship,"Louth, Carlingford Lough, across channel fairw...",12/11/1936,54.04722,-6.15333,"UKHO wreck no. 007600070. 328-ton, 29-year-old...",wrecks
79,Retriever (SS),W00080,Steamship,"Louth, Carlingford Bar, 800m SE of. Carlingfor...",03/11/1916,54.01717,-6.05767,"UKHO wreck no. 007600045, listed as a dangero...",wrecks
111,Unknown,W00112,Unknown,"Louth, Carlingford Lough, Block House Island, ...",Unknown,54.02222,-6.08667,UKHO wreck number 007600069. Stranded wreck.,wrecks

In [21]:
#sites['geometry'] = sites.apply(lambda z: Point(z.Lon, z.Lat), axis=1)
#sites = gp.GeoDataFrame(sites)

In [11]:
#smr['unique_id'] = df.longstrings.map(hash)

In [12]:
#sites.shape
print(smr.shape[0], 'maped sites')

154274 maped sites

In [13]:
#class_keys = ['RATH']
class_keys = ['RATH', 'CASH', 'RIFO', 'TOHO']
#class_keys = [ 'TOHO']

In [14]:
#sites_filtered = sites[sites['CLASSCODE'].isin(class_keys)]
smr_filtered = smr_cleaned

In [15]:
print(smr_filtered.shape[0], ' sites_filtered')

154274  sites_filtered

In [16]:
smr_filtered.head()

,CLASSCODE,CLASSDESC,SMRS,TLAND_NAMES,lat,lng,Link,title,type
0,PROM,Promontory fort - coastal,WI031-111----,DUNBUR HEAD,52.965537,-5.999549,http://webgis.archaeology.ie/HistoricEnvironme...,Saint Tiernan's Catholic Church,smr
1,PROM,Promontory fort - coastal,WI031-110----,DUNBUR HEAD,52.958482,-6.005486,http://webgis.archaeology.ie/HistoricEnvironme...,McMorrow's,smr
2,CHUR,Church,WI025-017001-,DUNBUR HEAD,52.972190,-6.008727,http://webgis.archaeology.ie/HistoricEnvironme...,Crossmolina Glebe House or Crossmolina Rectory,smr
3,CAVE,Cave,WI025-038----,DUNBUR HEAD,52.972184,-6.008906,http://webgis.archaeology.ie/HistoricEnvironme...,NaN,smr
4,PROM,Promontory fort - coastal,WI025-109----,DUNBUR HEAD,52.972107,-6.010160,http://webgis.archaeology.ie/HistoricEnvironme...,NaN,smr

## Persist to DB

In [18]:
smr_filtered.to_sql(name='smr', con=cnx, if_exists = 'append', index=True)

In [22]:
niah_filtered =  niah_cleaned
niah_filtered.to_sql(name='niah', con=cnx, if_exists = 'append', index=True)

In [17]:
wrecks_cleaned.to_sql(name='wrecks', con=cnx, if_exists = 'append', index=True)